version: '3'
services:
  app:
    container_name: docker-node-mongo
    build: .
    environment:
      - PORT=3001
      - MONGO_DATABASE=mongodb://mongodb:27017/xendit
    volumes:
      - .:/usr/src/app/docker-node-mongo
      - /usr/src/app/docker-node-mongo/node_modules/
    ports:
      - '3001:3001'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
